export const PDF_STORAGE_BUCKET_NAME = process.env.PDF_STORAGE_BUCKET_NAME;
export const ALLOWED_CORS_DOMAIN = process.env.ALLOWED_CORS_DOMAIN;
export const PDF_STORAGE_BUCKET_REGION = process.env.AWS_REGION;
